import BLEPeripheral from 'react-native-ble-peripheral';
import CryptoJS from 'crypto-js';
import { Buffer } from 'buffer';

const MANUFACTURER_ID = 0xFFFF;

class BleBroadcaster {
  public isAdvertising = false;
  private currentUserId = 'user_1234567890'; // Mock user phone number / ID

  async startSOSBeacon() {
    // Original SOS generated by this device (HopCount = 0)
    await this.startBroadcast(0x01, this.currentUserId, Math.floor(Date.now() / 1000), 0);
  }

  async startRelayBeacon(intentFlag: number, hashedDid: string, timestamp: number, hopCount: number) {
    // Re-broadcasting someone else's SOS (HopCount > 0)
    await this.startBroadcast(intentFlag, hashedDid, timestamp, hopCount, true);
  }

  private async startBroadcast(
    intentFlag: number, 
    userIdOrHash: string, 
    timestamp: number, 
    hopCount: number,
    isRelay: boolean = false
  ) {
    if (this.isAdvertising) this.stopBeacon();
    
    try {
      const payload = this.constructPayload(intentFlag, userIdOrHash, timestamp, hopCount, isRelay);
      const base64Payload = payload.toString('base64');
      
      if ((BLEPeripheral as any).addManufacturerData) {
        (BLEPeripheral as any).addManufacturerData(MANUFACTURER_ID, base64Payload);
      } else {
        BLEPeripheral.setName(base64Payload);
      }

      await BLEPeripheral.start();
      this.isAdvertising = true;
      console.log(`Started broadcasting ${isRelay ? 'RELAY' : 'SOS'} payload:`, base64Payload);
    } catch (error) {
      console.error('Failed to start beacon', error);
    }
  }

  stopBeacon() {
    if (!this.isAdvertising) return;
    try {
      BLEPeripheral.stop();
      this.isAdvertising = false;
    } catch (error) {
      console.error('Failed to stop beacon', error);
    }
  }

  private constructPayload(
    intentFlag: number, 
    userIdOrHash: string, 
    timestamp: number, 
    hopCount: number,
    isRelay: boolean
  ): Buffer {
    // 16 bytes total now
    const buffer = Buffer.alloc(16);
    
    // Bytes 0-1: 0xFFFF (Custom Manufacturer ID)
    buffer.writeUInt16LE(MANUFACTURER_ID, 0);
    
    // Byte 2: Intent Flag
    buffer.writeUInt8(intentFlag, 2);
    
    // Bytes 3-10: First 8 bytes of SHA-256 hashed User ID
    let hashHex = userIdOrHash;
    if (!isRelay) {
      // If originating, we need to hash it. If relaying, it's already a hash string.
      hashHex = CryptoJS.SHA256(userIdOrHash).toString(CryptoJS.enc.Hex);
    }
    const hashBuffer = Buffer.from(hashHex, 'hex');
    hashBuffer.copy(buffer, 3, 0, 8);
    
    // Bytes 11-14: UNIX Timestamp (4-byte Int32)
    buffer.writeInt32LE(timestamp, 11);
    
    // Byte 15: Hop Count
    buffer.writeUInt8(hopCount, 15);
    
    return buffer;
  }
}

export const BleBroadcasterService = new BleBroadcaster();
